[package]
name = "typograf-client"
version = "0.1.1"
authors = ["Nikita Hismatov <hismatovns@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", default-features = false }
